using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SoundState
{
    UI_CLICK,
    BACKGROUND_MUSIC_NIVEAUX,
    BACKGROUND_MUSIC_MENU,
    BACKGROUND_SFX_INSIDE_THE_STORE_AIRCLEMATISE,
    SFX_VALVE,
    SFX_PORTE,
    SFX_PRESSURE_PLATE,
    SFX_GOUTELETTE_EAU_VALVE,
    SFX_HUMAN_FOOTSTEPS,
    SFX_HUMAN_GRUNT_HURT,
    SFX_RACOON_IDLE,
    SFX_RACOON_WALK,
    SFX_RACOON_HIT,
    SFX_EAU_QUI_TRAVERSE_LES_TUYAUX,
    
    MUSIC
}